export type KeygenData = {
  box: "brown" | "one" | "two"; // Box the card is located in
  type: "person" | "talk"; // Person or talk card
  label?: string; // Label for the card, used for testing
  isPersonSpeaker?: boolean; // Is this a speaker?
  talkName?: string; // Name of the talk
  talkStage?: string;
  talkSpeaker?: string; // Speaker of the talk
  talkDescription?: string; // Description of the talk
  talkStartTime?: string; // Start time of the talk ex: 09:00
  talkEndTime?: string; // End time of the talk ex: 10:00
  talkTime?: Date;
};

export const initialKeygenData: Record<string, KeygenData> = {};

export const initialLocationData: Record<string, KeygenData> = {
  TALK01: {
    box: "brown",
    type: "talk",
    label: "talk 1",
    talkName: "The Future of Reth",
    talkStage: "Reth Updates",
    talkDescription: `Reth Updates`,
    talkSpeaker: "gakonst",
    talkStartTime: "9:00AM",
    talkEndTime: "9:30AM",
    talkTime: new Date("2024-08-16T09:00:00"),
  },
  TALK02: {
    box: "brown",
    type: "talk",
    label: "talk 2",
    talkName: "The Reth SDK",
    talkStage: "Reth Updates",
    talkDescription: `Reth Updates`,
    talkSpeaker: "mattsse_ & rjected",
    talkStartTime: "9:30AM",
    talkEndTime: "10:00AM",
    talkTime: new Date("2024-08-16T09:30:00"),
  },
  TALK03: {
    box: "brown",
    type: "talk",
    label: "talk 3",
    talkName: "Reth Execution Extensions",
    talkStage: "Reth Updates",
    talkDescription: `Reth Updates`,
    talkSpeaker: "shekhirin",
    talkStartTime: "10:00AM",
    talkEndTime: "10:30AM",
    talkTime: new Date("2024-08-16T10:00:00"),
  },
  TALK04: {
    box: "brown",
    type: "talk",
    label: "talk 4",
    talkName: "Reth to 1 Gigagas/s and Beyond",
    talkStage: "Reth Updates",
    talkDescription: `Reth Updates`,
    talkSpeaker: "rkrasiuk & danipopes",
    talkStartTime: "10:30AM",
    talkEndTime: "11:00AM",
    talkTime: new Date("2024-08-16T10:30:00"),
  },
  TALK05: {
    box: "brown",
    type: "talk",
    label: "talk 5",
    talkName: "Reth Core Development",
    talkStage: "Reth Updates",
    talkDescription: `Reth Updates`,
    talkSpeaker: "onbjerg",
    talkStartTime: "11:00AM",
    talkEndTime: "11:30AM",
    talkTime: new Date("2024-08-16T11:00:00"),
  },
  TALK06: {
    box: "brown",
    type: "talk",
    label: "talk 6",
    talkName: "Kona: no_std OP Stack state transition and derivation",
    talkStage: "Ecosystem Builders",
    talkDescription: `Ecosystem Builders`,
    talkSpeaker: "vex_0x",
    talkStartTime: "12:30PM",
    talkEndTime: "12:50PM",
    talkTime: new Date("2024-08-16T12:30:00"),
  },
  TALK07: {
    box: "brown",
    type: "talk",
    label: "talk 7",
    talkName: "SP1 Reth: Reth x ZK",
    talkStage: "Ecosystem Builders",
    talkDescription: `Ecosystem Builders`,
    talkSpeaker: "pumatheuma",
    talkStartTime: "12:50PM",
    talkEndTime: "1:10PM",
    talkTime: new Date("2024-08-16T12:50:00"),
  },
  TALK08: {
    box: "brown",
    type: "talk",
    label: "talk 8",
    talkName: "Pevm: Parallel EVM for Reth",
    talkStage: "Ecosystem Builders",
    talkDescription: `Ecosystem Builders`,
    talkSpeaker: "hai_rise",
    talkStartTime: "1:10PM",
    talkEndTime: "1:30PM",
    talkTime: new Date("2024-08-16T13:10:00"),
  },
  TALK09: {
    box: "brown",
    type: "talk",
    label: "talk 9",
    talkName: "Data Ecosystem Safari",
    talkStage: "Tooling",
    talkDescription: `Tooling`,
    talkSpeaker: "notnotstorm",
    talkStartTime: "9:00AM",
    talkEndTime: "9:30AM",
    talkTime: new Date("2024-08-17T09:00:00"),
  },
  TALK10: {
    box: "brown",
    type: "talk",
    label: "talk 10",
    talkName: "Foundry Endgame",
    talkStage: "Tooling",
    talkDescription: `Tooling`,
    talkSpeaker: "zerosnacks",
    talkStartTime: "9:30AM",
    talkEndTime: "10:00AM",
    talkTime: new Date("2024-08-17T09:30:00"),
  },
  TALK11: {
    box: "brown",
    type: "talk",
    label: "talk 11",
    talkName: "Alloy is ready for production",
    talkStage: "Tooling",
    talkDescription: `Tooling`,
    talkSpeaker: "yashatreya",
    talkStartTime: "10:00AM",
    talkEndTime: "10:30AM",
    talkTime: new Date("2024-08-17T10:00:00"),
  },
  TALK12: {
    box: "brown",
    type: "talk",
    label: "talk 12",
    talkName: "Modern JS for Ethereum",
    talkStage: "Tooling",
    talkDescription: `Tooling`,
    talkSpeaker: "awkweb",
    talkStartTime: "10:30AM",
    talkEndTime: "11:00AM",
    talkTime: new Date("2024-08-17T10:30:00"),
  },
  TALK13: {
    box: "brown",
    type: "talk",
    label: "talk 13",
    talkName: "Reth Benchmarking",
    talkStage: "Tooling",
    talkDescription: `Tooling`,
    talkSpeaker: "BrianBland",
    talkStartTime: "11:00AM",
    talkEndTime: "11:30AM",
    talkTime: new Date("2024-08-17T11:00:00"),
  },
  TALK14: {
    box: "brown",
    type: "talk",
    label: "talk 14",
    talkName: "Shadow Reth: Execution Extensions for Shadow Logs",
    talkStage: "Ecosystem Builders",
    talkDescription: "Ecosystem Builders",
    talkSpeaker: "emhsia",
    talkStartTime: "12:30PM",
    talkEndTime: "12:50PM",
    talkTime: new Date("2024-08-17T12:30:00"),
  },
  TALK15: {
    box: "brown",
    type: "talk",
    label: "talk 15",
    talkName: "RBuilder: A MEV Builder on Reth",
    talkStage: "Ecosystem Builders",
    talkDescription: "Ecosystem Builders",
    talkSpeaker: "ferranbt",
    talkStartTime: "12:50PM",
    talkEndTime: "1:10PM",
    talkTime: new Date("2024-08-17T12:50:00"),
  },
  TALK16: {
    box: "brown",
    type: "talk",
    label: "talk 16",
    talkName: "MEV RS",
    talkStage: "Ecosystem Builders",
    talkDescription: "Ecosystem Builders",
    talkSpeaker: "ralexstokes",
    talkStartTime: "1:10PM",
    talkEndTime: "1:30PM",
    talkTime: new Date("2024-08-17T13:10:00"),
  },
  TALK17: {
    box: "brown",
    type: "talk",
    label: "talk 17",
    talkName:
      "Brontes: How Chasing MEV Led to a General Purpose Blockchain Analytics Engine",
    talkStage: "Ecosystem Builders",
    talkDescription: "Ecosystem Builders",
    talkSpeaker: "0xvanbeethoven & Will Smith",
    talkStartTime: "1:30PM",
    talkEndTime: "1:50PM",
    talkTime: new Date("2024-08-17T13:30:00"),
  },
};
